create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  scholar_role text check (scholar_role in ('founder', 'creative', 'educator', 'professional', 'student', 'builder')),
  primary_focus text,
  experience_level text not null default 'explorer' check (experience_level in ('explorer', 'operator', 'builder')),
  capstone_goal text check (char_length(capstone_goal) <= 420),
  weekly_commitment text not null default 'focused' check (weekly_commitment in ('steady', 'focused', 'intensive')),
  onboarding_completed boolean not null default false,
  onboarding_completed_at timestamptz,
  cohort_code text not null default 'COHORT-001',
  role text not null default 'learner' check (role in ('learner', 'facilitator')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lesson_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_day integer not null check (lesson_day between 1 and 21),
  status text not null default 'started' check (status in ('started', 'completed')),
  score integer check (score between 0 and 100),
  evidence_url text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, lesson_day)
);

alter table public.profiles enable row level security;
alter table public.lesson_progress enable row level security;

grant select, insert, update on table public.profiles to authenticated;
grant select, insert, update on table public.lesson_progress to authenticated;
grant usage, select on sequence public.lesson_progress_id_seq to authenticated;

create policy "Learners can read their own profile"
on public.profiles for select
to authenticated
using ((select auth.uid()) = id);

create policy "Learners can create their own profile"
on public.profiles for insert
to authenticated
with check ((select auth.uid()) = id and role = 'learner');

create policy "Learners can update their own profile"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id and role = 'learner');

create policy "Learners can read their own progress"
on public.lesson_progress for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Learners can add their own progress"
on public.lesson_progress for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Learners can update their own progress"
on public.lesson_progress for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create schema if not exists private;

create or replace function private.create_academy_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

revoke all on function private.create_academy_profile() from public, anon, authenticated;

drop trigger if exists on_academy_user_created on auth.users;
create trigger on_academy_user_created
  after insert on auth.users
  for each row execute procedure private.create_academy_profile();
